[workspace]
authors = ["D. Kamensky"]
name = "tigar"
channels = ["conda-forge/label/fenics-dev", "conda-forge"]
platforms = ["linux-64"]
version = "2019.2"

[dependencies]
python = "3.10.*"
fenics = "==2019.2.0.dev20240219"
mpich = "*"
petsc4py = "*"
numpy = "*"
scipy = "*"
matplotlib = "*"
setuptools = "<81"
sphinx = "*"
pip = "*"

[pypi-dependencies]
tigar = { path = ".", editable = true }
igakit = { git = "https://github.com/dalcinl/igakit.git" }

[tasks]
docs = "python -m sphinx -b html docs docs/_build/html"
